//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// PTool.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_PToolTYPE                   130
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_PROPERTIES_WND              158
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDD_EffToolForm                 310
#define IDD_CreatePlane                 314
#define IDC_BTN_CREATEPLANE             1000
#define IDC_EDIT_WIDTH                  1001
#define IDC_BTN_CREATEOBJECT            1001
#define IDC_EDIT_HEIGHT                 1002
#define IDC_CHECK_IsLoop                1005
#define IDC_Btn_SelectTexture           1006
#define IDC_CHECK_IsBlended             1007
#define IDC_Btn_SelectScript            1009
#define IDC_ScriptList                  1011
#define IDC_EDIT_FrameInterval          1012
#define IDC_EDIT_LifeTime               1013
#define IDC_EDIT_XOffset                1014
#define IDC_EDIT_XInit                  1015
#define IDC_EDIT_YInit                  1016
#define IDC_EDIT_YOffset                1017
#define IDC_EDIT_Tx                     1020
#define IDC_EDIT_Ty                     1021
#define IDC_EDIT_Tz                     1022
#define IDC_EDIT_Rx                     1023
#define IDC_EDIT_Ry                     1024
#define IDC_EDIT_Rz                     1025
#define IDC_EDIT_Sx                     1026
#define IDC_EDIT_Sy                     1027
#define IDC_EDIT_Sz                     1028
#define IDC_EDIT_PlaneName              1029
#define IDC_EDIT1_XCount                1031
#define IDC_EDIT_YCount                 1032
#define IDC_BUTTON1                     1033
#define IDC_Btn_Save                    1033
#define IDC_BUTTON2                     1034
#define IDC_Btn_Load                    1034
#define IDC_EDIT_TextureWidth           1037
#define IDC_EDIT_TextureHeight          1038
#define IDC_Btn_Initialize              1039
#define IDC_COMBO_BLEND_SRC             1042
#define IDC_CHECK_BLEND                 1043
#define IDC_COMBO_BLEND_DEST            1044
#define IDC_CHECK_IsMultiTexture        1045
#define IDC_EDIT_FadeIn                 1046
#define IDC_EDIT_FadeOut                1047
#define IDC_Btn_EffectApply             1048
#define IDC_COMBO_PlaneList             1049
#define IDC_Btn_Refresh                 1050
#define IDC_EDIT_VeloY                  1051
#define IDC_EDIT_VeloX                  1052
#define IDC_EDIT_VeloZ                  1053
#define IDC_EDIT_Gravity                1054
#define IDC_EDIT_LaunchTime             1055
#define IDC_Btn_ObjectApply             1056
#define IDC_EDIT_Object_Tx              1057
#define IDC_EDIT_Object_Ty              1058
#define IDC_EDIT_Object_Tz              1059
#define IDC_EDIT_Object_Rx              1060
#define IDC_EDIT_Object_Ry              1061
#define IDC_EDIT_Object_Rz              1062
#define IDC_EDIT_Object_Sx              1063
#define IDC_EDIT_Object_Sy              1064
#define IDC_EDIT_Object_Sz              1065
#define IDC_COMBO_ObjectList            1066
#define IDC_Btn_RefreshObj              1067
#define IDC_EDIT_AxisX                  1068
#define IDC_EDIT_AxisY                  1069
#define IDC_EDIT_AxisZ                  1070
#define IDC_EDIT_Radius                 1071
#define IDC_CHECK_ClockWise             1072
#define IDC_EDIT_Speed                  1073
#define IDC_CHECK1                      1074
#define IDC_EDIT_EffTx                  1075
#define IDC_EDIT_EffTy                  1076
#define IDC_EDIT_EffTz                  1077
#define IDC_EDIT_EffSx                  1078
#define IDC_EDIT_EffSy                  1079
#define IDC_EDIT_EffSz                  1080

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        316
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
